### ISSUE TITLE
Flow error when a custom generator's dependencies contains a non-flow-degen import

### ISSUE THREAD

**Issue by gyrfalcon** [LoganBarnett/flow-degen#12]
I've created a [branch](/gyrfalcon/flow-degen/tree/import-flow-error) in my fork that exercises this issue, but in summary, if I have something like this:

```javascript
const customDegen = <CustomType: string, CustomImport: string>(
  refinerType: MetaType<CustomType, CustomImport>,
  refinerGenerator: DeserializerGenerator<CustomType, CustomImport>,
) => {
  const [refinerCode, deps] = refinerGenerator
  const header = typeHeader(refinerType)

  return [
    () => {
      return `
        (x: mixed): ${header} | Error => {
          const refiner = ${refinerCode()}
          return refiner(importedFn())
        }
      `
    },
    mergeDeps<CustomType, CustomImport>(
      deps,
      { types: [], imports: ['importedFn'], hoists: [] },
    ),
  ]
}
```

The following error results:

```console
$ yarn flow
yarn run v1.19.0
$ /Users/justin.shepard/Development/third-party-repos/flow-degen/node_modules/.bin/flow
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ test/custom-import.js:44:30

Cannot call mergeDeps with object literal bound to b because string [1] is incompatible with enum [2] in array element
of property imports.

     test/custom-import.js
     41│     },
     42│     mergeDeps<CustomType, CustomImport>(
     43│       deps,
 [1] 44│       { types: [], imports: ['importedFn'], hoists: [] },
     45│     ),
     46│   ]
     47│ }

     src/generator.js
 [2] 40│   imports: Array<DeImport | CustomImport>,
```

Running the generator doesn't have any errors, and flow is happy with the resultant refiner, it's just the generator itself that flow doesn't like. It's slightly happier if the `'importedFn'` string is changed to something `flow-degen` provides, like `'stringify'`. It seems to be related to `mergeDeps` as if you comment out lines 42, 43 and 45 flow is happy (though the test fails at that point).

**Comment by LoganBarnett** [comment]
We had some discussion about this. I think this can be a little confusing. The `CustomImport: string` that we see all over the generators is basically saying that `CustomImport` is _constrained by_ `string` and not a type alias of `string`. This allows us to do `string` things with `CustomImport`, but since it's an externally provided type, it could be further constrained by other things.

As far as a fix goes, @gyrfalcon will need to remove `CustomImport` (and possibly `CustomType`), and instead use the application-specific types that `CustomImport` and `CustomType` are meant to represent. This means in the custom generator the type params should be stripped from `customDegen`.

I'll leave this open for now - I feel like the actionable thing to do here is to document the expectations, and, I think, correct the type signature used in the custom generator example.

**Comment by gyrfalcon** [comment]
Just wanted to update this here, the project where I was running into this issue has been updated to use app-specific `Type` and `Import` values and the flow errors are gone.

I also updated the branch linked above with changes that get flow to pass. If desired I can turn that into a PR so there's a test for this.

**Comment by LoganBarnett** [comment]
Retroactive tests for existing behavior (and docs to go with it?!) are always appreciated!

**Comment by LoganBarnett** [comment]
The related pull request (#14) has been merged so this should be addressed now. Closing.
