### ISSUE TITLE
Intersection of degenField, degenRefiner and opaque type causes error

### ISSUE THREAD

**Issue by gyrfalcon** [LoganBarnett/flow-degen#17]
This could be a case of PEBCAK, but I was using opaque types and ran into an issue with flow finding an error in the resultant generated file. The types look (approximately) like this:

```javascript
opaque type MyCustomId = string

export type MyObject = {
  id: MyCustomId,
}
```

There's a custom refiner in the same file as the opaque type that looks like this:

```javascript
export const refineMyCustomId = (x: mixed) => MyCustomId | Error {
  return deString(x)
}
```

and then in a separate file the following generator:

```javascript
export const genRefineMyObject = () => degenObject(
  { name: 'MyObject', typeParams: [] },
  [degenField('id', degenRefiner('refineMyCustomId'))],
  [],
)
```

The generated refiner has the following error:

```console
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ my-object-refiner.js:52:13

Cannot call deField with refineMyCustomId bound to deserializer because string [1] is incompatible with
Error [2] in the return value.

     my-object-refiner.js
     49│         } else {
     50│           const id = deField(
     51│             'id',
     52│             refineMyCustomId,
     53│             json.id,
     54│           )
     55│           if (refineMyCustomId instanceof Error) {

     node_modules/flow-degen/src/deserializer.js
 [2] 34│   deserializer: (a: mixed) => (T | Error),

     my-object.js
 [1] 25│ export const refineMyCustomId = (x: mixed): MyCustomId | Error => {
```

The only workaround I've found so far is to manually edit the generated file like so:

```javascript
const id = deField<MyCustomId>(
  'id',
  refineMyCustomId,
  json.id,
)
```

Which is not ideal, as the change will be reverted the next time the refiner is regenerated.

**Comment by LoganBarnett** [comment]
1: I think always adding the type onto the call site is a good move going forward, since it takes the guesswork out of when Flow's inferencing is okay or will result in an error. It would fix some other errors we've seen but not had a chance to address. Perhaps it's time to do that pass with `typeHeader` everywhere?

2: Line 55 of your generated code (seen in the error) looks _very wrong_. If `refineMyCustomId` is the function to refine the `MyCustomId` value, then checking to see if the function is an `Error` means we've clearly got another bug. Acknowledging your earlier comment though: This could be that in the course of anonymizing/simplifying your error code, the identifier got picked up in a search/replace? It would be good to verify so we know if we have two bugs instead of one :)

**Comment by gyrfalcon** [comment]
> 1: I think always adding the type onto the call site is a good move going forward, since it takes the guesswork out of when Flow's inferencing is okay or will result in an error. It would fix some other errors we've seen but not had a chance to address. Perhaps it's time to do that pass with `typeHeader` everywhere?

That does feel like the right approach.
 
> 2: Line 55 of your generated code (seen in the error) looks _very wrong_. If `refineMyCustomId` is the function to refine the `MyCustomId` value, then checking to see if the function is an `Error` means we've clearly got another bug. Acknowledging your earlier comment though: This could be that in the course of anonymizing/simplifying your error code, the identifier got picked up in a search/replace? It would be good to verify so we know if we have two bugs instead of one :)

This is the result of my anonymizing the example, I replaced the wrong thing with the function name and didn't realize it. The variable being checked in the `if` in the non-anonymized code is `id` not `refineMyCustomId`.
